apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: encryption-deployment
  labels:
    app: encryption
spec:
  selector:
    matchLabels:
      app: encryption
  replicas: 1
  template:
    metadata:
      labels:
        app: encryption
    spec:
      containers:
      - name: encryption
        image: local/encryption-service
        imagePullPolicy: Always
        ports:
        - name: encryption
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: encryption
spec:
  type: ClusterIp
  selector:
    app: encryption
  ports:
  - port: 3000

---

apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: encryption
data:
  port: 3000

---

apiVersion: v1
kind: Ingress
metadata:
  name: encryption-ingress
  namespace: default
spec:
  rules:
  - host: encryption.roomone.com
    http:
      paths:
      - backend:
          serviceName: encryption
          servicePort: 3000

---

apiVersion: v1
kind: StatefulSet
metadata:
  name: encryption
spec:
  serviceName: "encryption"
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      labels:
        app: encryption
    spec:
      containers:
      - name: encryption
        image: localhost/encryption
        ports:
        - containerPort: 3000