// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/encryption.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestText struct {
	PlainMessage         string   `protobuf:"bytes,1,opt,name=plainMessage" json:"plainMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestText) Reset()         { *m = RequestText{} }
func (m *RequestText) String() string { return proto.CompactTextString(m) }
func (*RequestText) ProtoMessage()    {}
func (*RequestText) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_d6ec9fca786a6488, []int{0}
}
func (m *RequestText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestText.Unmarshal(m, b)
}
func (m *RequestText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestText.Marshal(b, m, deterministic)
}
func (dst *RequestText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestText.Merge(dst, src)
}
func (m *RequestText) XXX_Size() int {
	return xxx_messageInfo_RequestText.Size(m)
}
func (m *RequestText) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestText.DiscardUnknown(m)
}

var xxx_messageInfo_RequestText proto.InternalMessageInfo

func (m *RequestText) GetPlainMessage() string {
	if m != nil {
		return m.PlainMessage
	}
	return ""
}

type EncryptedText struct {
	EncryptedMessage     string   `protobuf:"bytes,1,opt,name=encryptedMessage" json:"encryptedMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedText) Reset()         { *m = EncryptedText{} }
func (m *EncryptedText) String() string { return proto.CompactTextString(m) }
func (*EncryptedText) ProtoMessage()    {}
func (*EncryptedText) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_d6ec9fca786a6488, []int{1}
}
func (m *EncryptedText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedText.Unmarshal(m, b)
}
func (m *EncryptedText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedText.Marshal(b, m, deterministic)
}
func (dst *EncryptedText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedText.Merge(dst, src)
}
func (m *EncryptedText) XXX_Size() int {
	return xxx_messageInfo_EncryptedText.Size(m)
}
func (m *EncryptedText) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedText.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedText proto.InternalMessageInfo

func (m *EncryptedText) GetEncryptedMessage() string {
	if m != nil {
		return m.EncryptedMessage
	}
	return ""
}

type InputString struct {
	InitalInput          string   `protobuf:"bytes,1,opt,name=initalInput" json:"initalInput,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputString) Reset()         { *m = InputString{} }
func (m *InputString) String() string { return proto.CompactTextString(m) }
func (*InputString) ProtoMessage()    {}
func (*InputString) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_d6ec9fca786a6488, []int{2}
}
func (m *InputString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputString.Unmarshal(m, b)
}
func (m *InputString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputString.Marshal(b, m, deterministic)
}
func (dst *InputString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputString.Merge(dst, src)
}
func (m *InputString) XXX_Size() int {
	return xxx_messageInfo_InputString.Size(m)
}
func (m *InputString) XXX_DiscardUnknown() {
	xxx_messageInfo_InputString.DiscardUnknown(m)
}

var xxx_messageInfo_InputString proto.InternalMessageInfo

func (m *InputString) GetInitalInput() string {
	if m != nil {
		return m.InitalInput
	}
	return ""
}

type ReveresedString struct {
	FinalOutput          string   `protobuf:"bytes,1,opt,name=finalOutput" json:"finalOutput,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReveresedString) Reset()         { *m = ReveresedString{} }
func (m *ReveresedString) String() string { return proto.CompactTextString(m) }
func (*ReveresedString) ProtoMessage()    {}
func (*ReveresedString) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_d6ec9fca786a6488, []int{3}
}
func (m *ReveresedString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReveresedString.Unmarshal(m, b)
}
func (m *ReveresedString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReveresedString.Marshal(b, m, deterministic)
}
func (dst *ReveresedString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReveresedString.Merge(dst, src)
}
func (m *ReveresedString) XXX_Size() int {
	return xxx_messageInfo_ReveresedString.Size(m)
}
func (m *ReveresedString) XXX_DiscardUnknown() {
	xxx_messageInfo_ReveresedString.DiscardUnknown(m)
}

var xxx_messageInfo_ReveresedString proto.InternalMessageInfo

func (m *ReveresedString) GetFinalOutput() string {
	if m != nil {
		return m.FinalOutput
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestText)(nil), "proto.RequestText")
	proto.RegisterType((*EncryptedText)(nil), "proto.EncryptedText")
	proto.RegisterType((*InputString)(nil), "proto.InputString")
	proto.RegisterType((*ReveresedString)(nil), "proto.ReveresedString")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EncryptionServiceClient is the client API for EncryptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EncryptionServiceClient interface {
	Encrypt(ctx context.Context, in *RequestText, opts ...grpc.CallOption) (*EncryptedText, error)
	Reverse(ctx context.Context, in *InputString, opts ...grpc.CallOption) (*ReveresedString, error)
}

type encryptionServiceClient struct {
	cc *grpc.ClientConn
}

func NewEncryptionServiceClient(cc *grpc.ClientConn) EncryptionServiceClient {
	return &encryptionServiceClient{cc}
}

func (c *encryptionServiceClient) Encrypt(ctx context.Context, in *RequestText, opts ...grpc.CallOption) (*EncryptedText, error) {
	out := new(EncryptedText)
	err := c.cc.Invoke(ctx, "/proto.EncryptionService/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionServiceClient) Reverse(ctx context.Context, in *InputString, opts ...grpc.CallOption) (*ReveresedString, error) {
	out := new(ReveresedString)
	err := c.cc.Invoke(ctx, "/proto.EncryptionService/Reverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EncryptionService service

type EncryptionServiceServer interface {
	Encrypt(context.Context, *RequestText) (*EncryptedText, error)
	Reverse(context.Context, *InputString) (*ReveresedString, error)
}

func RegisterEncryptionServiceServer(s *grpc.Server, srv EncryptionServiceServer) {
	s.RegisterService(&_EncryptionService_serviceDesc, srv)
}

func _EncryptionService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EncryptionService/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).Encrypt(ctx, req.(*RequestText))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionService_Reverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionServiceServer).Reverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EncryptionService/Reverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionServiceServer).Reverse(ctx, req.(*InputString))
	}
	return interceptor(ctx, in, info, handler)
}

var _EncryptionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EncryptionService",
	HandlerType: (*EncryptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _EncryptionService_Encrypt_Handler,
		},
		{
			MethodName: "Reverse",
			Handler:    _EncryptionService_Reverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/encryption.proto",
}

func init() { proto.RegisterFile("proto/encryption.proto", fileDescriptor_encryption_d6ec9fca786a6488) }

var fileDescriptor_encryption_d6ec9fca786a6488 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x10, 0x80, 0x5f, 0x07, 0x7d, 0x78, 0x55, 0xd4, 0x20, 0x45, 0x3a, 0x95, 0x4c, 0xe2, 0xd0, 0xa2,
	0x45, 0x1c, 0x9c, 0x3b, 0x38, 0x88, 0xd0, 0xfa, 0x07, 0x62, 0x7b, 0x96, 0x40, 0x49, 0x63, 0x72,
	0x2d, 0x3a, 0xfb, 0xc7, 0x85, 0xb4, 0xd6, 0x84, 0x37, 0x05, 0xbe, 0xf0, 0x1d, 0xf7, 0x1d, 0x24,
	0xda, 0x8c, 0x34, 0x16, 0xa8, 0x5a, 0xf3, 0xad, 0x49, 0x8e, 0x2a, 0x77, 0x80, 0x1d, 0xb9, 0x87,
	0xdf, 0x41, 0x5c, 0xe3, 0xe7, 0x84, 0x96, 0xde, 0xf0, 0x8b, 0x18, 0x87, 0x53, 0x3d, 0x08, 0xa9,
	0x5e, 0xd0, 0x5a, 0xd1, 0xe3, 0x75, 0x94, 0x45, 0x37, 0x27, 0x75, 0xc0, 0xf8, 0x13, 0x9c, 0x55,
	0xcb, 0x34, 0xec, 0x9c, 0x74, 0x0b, 0x17, 0xf8, 0x07, 0x42, 0xf1, 0x80, 0xf3, 0x02, 0xe2, 0x67,
	0xa5, 0x27, 0x6a, 0xc8, 0x48, 0xd5, 0xb3, 0x0c, 0x62, 0xa9, 0x24, 0x89, 0xc1, 0xc1, 0xd5, 0xf2,
	0x11, 0x2f, 0xe1, 0xbc, 0xc6, 0x19, 0x0d, 0x5a, 0xec, 0xfe, 0xa5, 0x0f, 0xa9, 0xc4, 0xf0, 0x3a,
	0x91, 0x27, 0x79, 0xe8, 0xfe, 0x27, 0x82, 0xcb, 0x6a, 0x2b, 0x6e, 0xd0, 0xcc, 0xb2, 0x45, 0xf6,
	0x00, 0xfb, 0x15, 0x32, 0xb6, 0x5c, 0x21, 0xf7, 0xda, 0xd3, 0xab, 0x95, 0x05, 0x71, 0x7c, 0xc7,
	0x1e, 0x61, 0xef, 0x36, 0xb0, 0xb8, 0x69, 0x5e, 0x42, 0x9a, 0x6c, 0xa3, 0x82, 0x2d, 0xf9, 0xee,
	0xfd, 0xd8, 0x7d, 0x94, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x2e, 0x9d, 0xa1, 0x83, 0x01,
	0x00, 0x00,
}
